[options]
; --- Seguridad y Base de Datos ---
admin_passwd = admin_dev
db_host = db
db_user = odoo
db_password = odoo
db_port = 5432

; --- Rutas de Addons (Tu Estándar) ---
; Asegúrate de que no haya espacios innecesarios entre las comas
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/opt/odoo/custom-addons

; --- Configuración de Red y Desarrollo ---
; Odoo 19 pide definir la interfaz (0.0.0.0 permite acceso externo al contenedor)
http_interface = 0.0.0.0
http_port = 8069
longpolling_port = 8072

; --- Logs ---
log_level = info
test_enable = False
without_demo = False